### ISSUE TITLE
Timezone Offset 

### ISSUE THREAD

**Issue by cmsdroff** [bic-org/Facility-Code#7]
When events occur in different timezones there needs to be a timezone offset provided for that location so that it can be aligned with the classical track and trace messages in use today, these are typically always in local time, similar to flights.

Consider the following:

Container arrives at a location in Shanghai and the classical tracking message provides 

`2020-06-20 04:00`

an IoT event is also received from another source which returns the following: 

`2020-06-19T20:00:00+08:00`
`2020-06-19T20:00:00Z`

These represent the same event in different ways, the first needs the context of the location to make it understandable.

In the API response we could provide the Timezone offset in a similar format to below:

`"offset": "UTC+08:00"`

```json
{
  "code": "CNSGHSECT",
  "codeProvider": "SMDG",
  "unLocode": "CNSGH",
  "countryCode": "CN",
  "offset": "UTC+08:00",
  "facility": {
    "name": "SHANGHAI EAST CONTAINER TERMINAL (WAIGAOQIAO PHASE 4)",
    "address": {
      "street": "-",
      "city": "-",
      "state": "-",
      "postcode": "-",
      "country": "-"
    },
    "formattedAddress": "-",
    "geographicalCoordinate": {
      "latitude": "-",
      "longitude": "-"
    }
  }
}
```

**Comment by nissimsan** [comment]
HI @cmsdroff - thanks from bringing my suggestion into the right place. I absolutely love that you pick this up!!

Some initial feedback: 

1. You need to distinguish between `timezone` and `timezoneOffset`. Timezone is for example `CET` whereas TimezoneOffset is `+01:00`. I suggest you include these as separate attributes, which will make them easier to use. 

2. The `timezone` is fixed for a location. A given terminal or depot or UNLOCODE is always placed in e.g. CET. So you can safely return those, and I believe this (UNLOCODE-to-timezone conversion) is your main value add. Like I said in my email, such a service does not exist anywhere. 

3. `timezoneOffset` on the other hand isn't fixed, but changes with daylight savings. Thus, CET can be either `+01:00` or `+02:00` depending on the time of year. This means that a timestamp has to be considered as input in order to determine offset. 
While this would be very convenient, it might be slightly further from your normal scope(?). And if you don't include this, other services can be used to turn a timezone+timestamp into an offset. 

Keep up the good work!!

**Comment by Chatissimus** [comment]
Hi,

if a timeZone liked to location is provided, the iana time zone identifier (like Europe/Paris) should be considered, in my side it's easier to manage it rather than standard offset (like CET/CEST), it avoids some confusion an it's more consistent through time

**Comment by djandyr** [comment]
I agree with comments from @nissimsan storing UTC offset will be tricky as it is not fixed. Timezones will be subject to Daylight Saving Time (DST) or change over time due to geopolitical reasons eg. Chile observed DST every year until a permanent UTC offset of -3 was introduced in 2015.

For the actual date (past) the offset for the time zone is known as the event has already happened. However, any estimated date (future) the offset could change by DST coming into effect.

From an API consumer perspective, the generic approach would be to provide UTC, local, and timezone to provide the ability for developers to convert UTC into their user's local time and/or display original local time and timezone.

```json
{
  "localDateTime": "2020-06-20 04:00:00",
  "timeZone": "Asia/Shanghai",
  "utcDateTime": "2020-06-19 20:00:00"
}
```

Local date time will allow the preservation of data that was originally supplied for classical tracking messages, as it's important to know that UTC has been derived from local date time and timezone. For IoT event, a blank local date-time and `Etc/UTC` timezone (as per IANA) would be expected.

**Comment by djandyr** [comment]
@cmsdroff  Just on your IoT event example would you only receive UTC offset? Daylight saving time will throw a spanner in the works on the determination of timezone solely from UTC offset.

**Comment by nissimsan** [comment]
Hi @djandyr et al.,

I agree on including the readable `"Asia/Shanghai"` style as well. I don't know much about this, but there must be a many-to-one relationship between this and the timezone, though, I think. Like, `"Europe/Copenhagen"` and `"Europe/Stockholm"` are both in `"CET"`. I think the distinction between these is `zone` and `timezone`, respectively. 
Ideally you'd include both, I suppose. I would encourage you to look at https://timezonedb.com/ for inspiration. Seems solid and whatever they take as input is likely a good indicator for you guys.  

We seem to agree that you shouldn't tackle specific timestamps, at least not as your primary service. But just as a comment to your example, note the ISO8601 notation convention: https://www.w3.org/TR/NOTE-datetime. 1) the date and time is separated by a `T` and 2) for a full date+time timezone offset is mandatory. For example `"localDateTime": "2020-06-20T04:00:00+08:00"`.
UTC is indicated with a `Z` like this: `"utcDateTime": "2020-06-19T20:00:00Z"`; as in your example if your IoT device operates in UTC only.

**Comment by djandyr** [comment]
Evening @nissimsan 

I agree on ISO8601 standard. I have a habit of quoting dates RFC 3389. The pointer to timezoneDB and their API does provide inspiration with good hints to terminology along with solid examples converting timezones.

Interesting point on time zone abbreviations. For example, my timezone BST can be interpreted as British Summer Time "Europe/London", or Bangladesh Standard Time "Asia/Dhaka". Time abbreviations are not unique identifiers, but paired with timezone does form a composite key.

Appreciate the direction on IoT devices using UTC only. As David has mentioned traditional tracking messages will provide local time value only without any offset. The timezone name and abbreviation are required relative to the event location to allow accurate determination of UTC.

Agreement forming on timezone name and abbreviation? @cmsdroff If only UN/LOCODE provided complete geocoding information to determine timezone from coordinates

```json
{
	"code": "CNSGHSECT",
	"codeProvider": "SMDG",
	"unLocode": "CNSGH",
	"countryCode": "CN",
	"timeZone": {
		"name": "Asia/Shanghai",
		"abbreviation": "CST"
	},
	"facility": {
		"name": "SHANGHAI EAST CONTAINER TERMINAL (WAIGAOQIAO PHASE 4)",
		"address": {
			"street": "-",
			"city": "-",
			"state": "-",
			"postcode": "-",
			"country": "-"
		},
		"formattedAddress": "-",
		"geographicalCoordinate": {
			"latitude": "-",
			"longitude": "-"
		}
	}
}
```

**Comment by cmsdroff** [comment]
Thanks for your comments on this thread, it's very interesting and much appreciated.  We will consider this in our review and we will for a facility such as a port or container facility be providing some kind of indicator, as the facilities are very much static and not part of a status event for example so seems more feasible here to provide the `timezone identifier` like `Europe/Paris` as you mention the facility is permanent in that location, and a lookup will help for the current time using this.  I will update once a decision is made.

Aside from this I also wanted to let you know I raised a request with the UN/LOCODE Re-Engineering team that they provide 2 things:

1. Lat/Long for all UNLOCODE's and backfill the dataset, this should be machine readable decimals.
2. API endpoint to lookup the "UNLOCODE-to-timezone conversion" @nissimsan I get the message loud and clear ;) 

Will report back on that front also.

**Comment by cmsdroff** [comment]
closing due to lack of activity
